### ISSUE TITLE
Getting error "Undefined namespace DependencyInjection"

### ISSUE THREAD

**Issue by victorbstan** [ramunasd/symfony-container-mocks#3]
I've installed the package using composer. But adding `use RDV\SymfonyContainerMocks\DependencyInjection\TestContainer;` Is giving me an error:  "Undefined namespace DependencyInjection". As if it can't find the package. Is there some way I can check if it's been installed properly, or some other configuration step that I'm missing perhaps?

To setup I've done:

```
"require-dev" : {
        "ramunasd/symfony-container-mocks": "*"
    },
```

And then I ran `composer install`.

**Comment by ramunasd** [comment]
Hi @victorbstan You can always check installed packs by running command `composer show`.
If it still not in Your vendor directory, then i'd suggest to update composer to latest stable version and then try add this tool with command `composer require ramunasd/symfony-container-mocks -vvv`. Hope that helps.

**Comment by ramunasd** [comment]
closing as there no feedback from opener
